version: '3.3'
services:
  mysql:
    image: mysql:8.0.24
    restart: always
    environment:
      MYSQL_DATABASE: 'comiclibrary'
      MYSQL_USER: 'albouser'
      MYSQL_PASSWORD: 'secretpassword'
      MYSQL_ROOT_PASSWORD: 'supersecretpassword'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - C:\Users\Jorge\Documents\Projects\java\docker-mysql\data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d