GET http://localhost/characters HTTP/1.1

### 

GET http://localhost/marvel/characters/capamerica HTTP/1.1

### 

GET http://localhost/marvel/characters/ironman HTTP/1.1
### 

GET http://localhost/marvel/characters/test HTTP/1.1
### 

# Consulta creators desde API Marvel y los persiste
GET http://localhost/marvel/characters/testSyncCreators HTTP/1.1