GET http://localhost/marvel/colaborators/capamerica HTTP/1.1
### 
GET http://localhost/marvel/colaborators/ironman HTTP/1.1

###






# Consulta creators desde API Marvel y los persiste
GET http://localhost/marvel/test/testSyncCreators HTTP/1.1
### 

GET http://localhost/marvel/test/testSyncCharacterByComic HTTP/1.1
### 

GET http://localhost/marvel/test/deleteComics HTTP/1.1
### 

GET http://localhost/marvel/test/deleteCreators HTTP/1.1
### 

GET http://localhost/marvel/test/deleteCharacters HTTP/1.1